version: "3"
services:
  box:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./src:/home/dev/src
    entrypoint: ["tail", "-f", "/dev/null"]  # Needed to keep the container running
